### ISSUE TITLE
Review issues

### ISSUE THREAD

**Issue by vr8hub** [dajare/r-m-ballantyne_the-coral-island#1]
- [x] The first mention of an author in the long description should be linked to his SE author page; see [SEMoS 9.6.2.5](https://standardebooks.org/manual/1.7.0/single-page#9.6.2.5). Thus, his name in the second paragraph should be tagged just as RLS' is.
- [x] We don't leave all caps in the text, for accessibility purposes; screen readers don't deal with them very well. The list in chapter 29 can be regular case, e.g. "Jack Martin," etc. The all-small-caps will still do the right thing.
- [x] The "anyone o' us" in chapter 22 should be left as "any one o' us".
- [x] The "Olive Branch" is a ship and so should have italic semantics, not `<em>`.
- [x] I'm not sure the "melee" in chapter 31 is emphasis; it looks more like it's italicized for non-English word purposes. I know it's not italicized in chapter 20 (the only other place it appears), but inconsistency is a hallmark of print publishing. :) I'll leave it to you to decide.
- [x] Same for the "debris" in ch. 17.
- [x] The instances of "Areoi", "aoa", and "taro" are not emphasis, either. They are either foreign, or possibly could fall under [SEMoS 8.2.10.1](https://standardebooks.org/manual/1.7.0/single-page#8.2.10.1). The "taboo", "maro", and "long pig" emphasis would appear to fall under the latter.
- [x] The bridgehead CSS (see [SEMoS 7.2.11.1](https://standardebooks.org/manual/1.7.0/single-page#7.2.11.1)) is missing from local.css.
- [x] The list of food in c17 is not bulleted in the source. Is there a reason to make it so here?
- [x] There are numerous instances of semi-colons being inside quotemarks, e.g. `"let us go and fetch it;"` unlike commas and periods, semi-colons go outside the quotes, e.g. `"let us go and fetch it";`. A simple regex should take care of it (editorial, of course, since it's changing content).

**Comment by dajare** [comment]
@vr8hub Super review - sharp eyes! :+1:  Just a bit of commentary on a few:

- `melee` and `debris` : I have removed the "italic" altogether. These look like old cases of "foreign" words, and I've made [the commit \[Editorial\]][1].
- all the "Areoi", "aoa", etc. items are now wrapped in `i` with the `xml:lang="fj"` semantics added.
- however, two occurrences did strike me on reflection as likely intending emphasis:
    - `long pig` in [chapter 25, line 29][2]
    - `long pig` in [chapter 29, line 22][3]
These are a bit of a judgment call, though, so see what you think.
- bridgehead : I think I've copied all that's needful from SEMoS. I did check other repos to see how much was included; I've left out the `poem/verse/song/hymn` bit, as I don't think that applies in this book.
- semicola/quotes : I did all those changes in [one \[Editorial\] commit][4]. It struck me that one or two cases used a semi-colon where we would expect a comma (e.g., `“Yes”; I replied.`, [ch. 8 line 69][5]), and other such cases do appear with comma! But, as you sagely observe, "inconsistency is a hallmark of print publishing", and I have left these as-is. If they should be revisited and the `;` replaced with `,` (and tweak the quotation mark), that can be done, of course ("\[Editorial\]").

I *think* that's it! Hopefully I've made the correct revisions. Time will tell!

[1]: https://github.com/dajare/r-m-ballantyne_the-coral-island/commit/47b855e0ae6e7b3a129a09220273af1fb6de882f 
[2]: https://github.com/dajare/r-m-ballantyne_the-coral-island/blob/47b855e0ae6e7b3a129a09220273af1fb6de882f/src/epub/text/chapter-25.xhtml#L29
[3]: https://github.com/dajare/r-m-ballantyne_the-coral-island/blob/47b855e0ae6e7b3a129a09220273af1fb6de882f/src/epub/text/chapter-29.xhtml#L22
[4]: https://github.com/dajare/r-m-ballantyne_the-coral-island/commit/ff73ebd1c8b7e455906dfa5ba8c58214b1289b37
[5]: https://github.com/dajare/r-m-ballantyne_the-coral-island/blob/47b855e0ae6e7b3a129a09220273af1fb6de882f/src/epub/text/chapter-8.xhtml#L69

**Comment by vr8hub** [comment]
Yeah, I'm OK with the emphasis on the two "long pig"s. That phrase and how it's used throughout is bit confusing overall, and I struggle with the right way to handle things like that anyway. Alex can change it if he disagrees. :)

Unless they're particularly egregious, we (I?) don't usually bother with punctuation differences. They're mostly subjective, and that subjectivity changes over time, and it's a pretty large rabbit hole once you find yourself in it. Things like "Why did he want to do that!" are common (should that be a question mark? Maybe! Or is that "Maybe?"). And so forth.

With those changes, lint now reports a couple of small issues; they should both be corrected. Once those are done, I think it's ready for Alex!

**Comment by dajare** [comment]
@vr8hub - Doh! I thought to run `se clean`, but stupidly assumed I needn't re-run `se lint`. Now I know better! 

Thanks for the comments, and the light-yet-firm touch in review. Really helpful. If you're content now, I guess it's over to Alex!

(P.s., while we're at it — it seems we've ["worked" together before][1]. That was me who poked away at your  "A. Æ. H." conundrum on your _epic_ Gibbon production. Congrats on that, by the way!)

**Comment by vr8hub** [comment]
Yeah, it took me several times to learn to _always_ run typogrify/semanticate/clean as the last thing before a review, and the last thing after making changes during a review. I would love to say I never forget…

Yes, I remember! :) That was a long two years, of which I think 80% of it was spent on the endnotes. Thanks!
